version: '3.5'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=3000
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
      - ./backend/uploads:/app/uploads
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-nginx-app
    ports:
      - '8080:80'

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres-demo
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nginx:
    image: nginx
    container_name: nginx-demo
    depends_on:
      - backend
      - frontend
    restart: always
    build: 
        context: ./frontend
    ports:
      - '80:80'
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
